{"uuid": "f5e63e29-1189-42af-9bb3-379f29fe10fd", "children": ["604db43c-7770-4001-9012-de4989f98492"], "befores": [{"name": "_Class__pytest_setup_method", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/python.py\", line 785, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/python.py\", line 703, in _call_with_optional_argument\n    func()\n  File \"/scipt/python/testerhome_pratice/appium_homework/test_xueqiu_webview.py\", line 31, in setup_method\n    self.driver.find_element_by_accessibility_id('已有蛋卷基金账户登录').click()\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py\", line 454, in find_element_by_accessibility_id\n    return self.find_element(by=MobileBy.ACCESSIBILITY_ID, value=accessibility_id)\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py\", line 270, in find_element\n    'value': value})['value']\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1558363856809, "stop": 1558363870187}], "start": 1558363856809, "stop": 1558363870279}